name: Deploy to Cloud Run

# Trigger workflow setiap push ke branch main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: udb-ti-24a1          # Ganti dengan Project ID kamu
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Step 3: Build Docker image dan push ke GCR
    - name: Build Docker image
      run: |
        gcloud builds submit --tag gcr.io/udb-ti-24a1/cloudrun-najwa-deploy-codelab

    # Step 4: Deploy image ke Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy cloudrun-najwa-deploy \
          --image gcr.io/udb-ti-24a1/cloudrun-najwa-deploy-codelab \
          --region us-west1 \
          --platform managed \
          --allow-unauthenticated
